// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/investment/:id": {
    params: {
      "id": string;
    };
  };
  "/investment/:id/due-diligence": {
    params: {
      "id": string;
    };
  };
  "/sponsor/:sponsorId/deals": {
    params: {
      "sponsorId": string;
    };
  };
  "/sponsor/:sponsorId/deals/:dealId": {
    params: {
      "sponsorId": string;
      "dealId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/investment/:id" | "/investment/:id/due-diligence" | "/sponsor/:sponsorId/deals" | "/sponsor/:sponsorId/deals/:dealId";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/investment.$id.tsx": {
    id: "routes/investment.$id";
    page: "/investment/:id";
  };
  "routes/investment.$id.due-diligence.tsx": {
    id: "routes/investment.$id.due-diligence";
    page: "/investment/:id/due-diligence";
  };
  "routes/sponsor.$sponsorId.deals.tsx": {
    id: "routes/sponsor.$sponsorId.deals";
    page: "/sponsor/:sponsorId/deals";
  };
  "routes/sponsor.$sponsorId.deals.$dealId.tsx": {
    id: "routes/sponsor.$sponsorId.deals.$dealId";
    page: "/sponsor/:sponsorId/deals/:dealId";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/home": typeof import("./src/routes/home.tsx");
  "routes/dashboard": typeof import("./src/routes/dashboard.tsx");
  "routes/investment.$id": typeof import("./src/routes/investment.$id.tsx");
  "routes/investment.$id.due-diligence": typeof import("./src/routes/investment.$id.due-diligence.tsx");
  "routes/sponsor.$sponsorId.deals": typeof import("./src/routes/sponsor.$sponsorId.deals.tsx");
  "routes/sponsor.$sponsorId.deals.$dealId": typeof import("./src/routes/sponsor.$sponsorId.deals.$dealId.tsx");
};